### ISSUE TITLE
Documentation for dev environment set up?

### ISSUE THREAD

**Issue by cweagans** [crc83/rallydev#16]
Is there some documentation like this? Or can you provide some steps that I can follow to get set up to work on this plugin? I understand Java pretty well, but I'm a little fuzzy on how to get this plugin to build in a way that I can test it locally.

If you can help me get set up, I'll spend some time updating the plugin for IntelliJ 15 and related products.

**Comment by crc83** [comment]
Well that's one of the reason I stop maintain this plugin gor new Intellij idea.
The configuration process is not straight forward.

**Comment by crc83** [comment]
Well I've tried to make this plugin at least compiling.
Changes required in build script:
1) remove bintray plugin and configuration
2) set proper path to IDEA (def ideaPath)
3) run tasks copyTasksJars copyIdeaJars copyRallyApi
4) Import into idea as a gradle project

**Comment by crc83** [comment]
Project reworked. I add documentation
